name: spatial-pca
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - rasterio
  - shapely
  - scikit-image
  - scikit-learn
  - pyyaml
  - pyogrio
  - notebook>=7
